version: "3"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.development
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx:1.25.2
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  database:
