name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: run type check
        run: npm run typecheck
      - name: run tests
        run: npm run test
